[build]
command = "npm run pages:build"
cwd = "."

pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "job-post-decoder"
route = ""

[env.staging]
name = "job-post-decoder-staging"
route = ""
